language: node_js
sudo: required
dist: trusty
services:
  - docker
script:
- docker run -t -i -v "$(pwd):/work" thumbsupgallery/thumbsup /bin/sh -c "cd /work/ && thumbsup --config config.json"
- ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  committer_from_gh: true
  keep_history: true
  github_token:  $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  fqdn: rent305.net
  on:
    branch: master
notifications:
  email: false